### ISSUE TITLE
Is this module capable to resend packet cpature from Wireshark?

### ISSUE THREAD

**Issue by wyxcoder** [nospaceships/node-raw-socket#61]
I capture a packet in Wireshark, can I send the packet to the network interface with the module.

I don't see where you set  which network interface to use ?

**Comment by stephenwvickers** [comment]
I am not sure how or if you can do this on Windows.  On Linux you have `SO_BINDTODEVICE`, but I don't thin that is available on Windows.

**Comment by fresheneesz** [comment]
I was looking for this as well. I specifically want to ping an address from each interface on my machine to see which are connected to the internet. Without a way to specify the network interface to use, I can't use the node-net-ping project.

**Comment by stephenwvickers** [comment]
@fresheneesz It depends on the socket type and the OS.  For UDP/TCP sockets you can bind to a local IP address, which ultimately means you control which IP address is used in the IP header.

For raw sockets, since you control the IP header, you could try specifying the source IP address in your data, and your OS may use this and route out the correct interface.

**Comment by stephenwvickers** [comment]
@fresheneesz Please remember the UDP/TCP sockets you can use in Node.js are NOT raw sockets, so don't behave in the same way or have the same features.

**Comment by fresheneesz** [comment]
@stephenwvickers That's fair. It would be pretty weird to me tho if the OS didn't allow you to choose what interface to use raw sockets with. That would be like offering a way to access a game controller, but only to one of them at random.
